document.write('<STYLE type=text/css>');
document.write('.ysmenu { color: #ff9900;font-size:12px}');
document.write('.ysmenu a:link { color: #666666; text-decoration: none}');
document.write('.ysmenu a:visited { color: #666666; text-decoration: none}');
document.write('.ysmenu a:hover {color: #FF9900; text-decoration: underline}');
document.write('a:visited.ysmenu{color:#666666;text-decoration:none}');
document.write('</STYLE>');
document.write('<table width=770 border=0 align=center cellpadding=0 cellspacing=0 bgcolor=#FFFFFF>');
document.write('<tr>');
document.write('<td>');
document.write('<a href=http://www.yinsha.com target=_top><img src=http://zj.yinsha.com/yinsha.gif width=84 height=17 border=0></a>');
document.write('</td>');
document.write('<td width=681 align=right class=ysmenu>');
document.write(' <a href=http://www.bliao.com target=_top>聊天</a>');
document.write('·<a href=http://card.yinsha.com target=_top>贺卡</a>');
document.write('·<a href=http://bbs.yinsha.com target=_top>论坛</a>');
document.write('·<a href=http://sms.yinsha.com target=_top>短信</a>');
document.write('·<a href=http://love.yinsha.com target=_top>交友</a>');
document.write('·<a href=http://diary.yinsha.com target=_top>日记</a>');
document.write('·<a href=http://album.yinsha.com target=_top>相册</a>');
document.write('·<a href=http://wind.yinsha.com target=_top>文学</a>');
document.write('·<a href=http://info.yinsha.com target=_top>供求</a>');
document.write('·<a href=http://alumni.yinsha.com target=_top>校友</a>');
document.write('·<a href=http://bookmark.yinsha.com target=_top>书签</a>');
document.write('·<a href=http://zj.yinsha.com target=_top>粤西</a>');
document.write('·<a href=http://zjphoto.yinsha.com/ target=_top>图片</a>');
document.write('·<a href=http://photo.yinsha.com target=_top>摄影</a>');
document.write('·<a href=http://ent.yinsha.com/ target=_top>娱乐</a>');
document.write('·<a href=http://life.yinsha.com/ target=_top>生活</a>');
document.write('·<a href=http://sports.yinsha.com/ target=_top>体育</a>');
document.write('·<a href=http://finance.yinsha.com/ target=_top>财经</a>');
document.write('·<a href=http://net.yinsha.com/ target=_top>导航</a>');
document.write('</td>');
document.write('</tr>');
document.write('</table>');